config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'conditions', to: 'pages#condition'
  get 'mentions-legales', to: 'pages#mentions'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post '/submit-code', to:'codes#submit'

  resources :hospitals, only: [:index, :new, :create] do
  	resources :free_beds, only: [:new, :create]
  end

  resources "contacts", only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :message, validate: true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: ENV["EMAIL_SUBJECT"],
      to: ENV["EMAIL_TO"],
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/free_bed.rb
class FreeBed < ApplicationRecord
	belongs_to :hospital

	# validates :number, inclusion: { in: 0..1000 }
end

app/models/hospital.rb
class Hospital < ApplicationRecord
	# belongs_to :owner, class_name: 'User'
  has_many :free_beds

	validates :name, presence: true
	validates :address, presence: true
	validates :status, presence: true, inclusion: { in: ['enabled', 'disabled'] }
	# accepts_nested_attributes_for :free_beds, allow_destroy: true

	geocoded_by :address
	after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
	# has_many :hospitals, foreign_key: :owner_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def code_valid?(code)
    return true if code == "1234"

    flash[:alert] = "Problème avec le code. Ce code n'existe pas."
    return false
  end

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:submit]
  def submit
    if verify_recaptcha
      if code_valid?(params[:code])
        session[:code] = params[:code]
        redirect_to hospitals_path
      else
        redirect_to root_path
      end
    else
      flash[:alert] = "Error about CATPCHA"
      redirect_to root_path
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Merci pour votre message, il nous a bien été envoyé.'
      redirect_to new_contact_path
    else
      flash[:alert] = "Erreur dans l'envoi du message."
      render :new
    end
  end

  private

  def contact_params
  	params.require(:contact).permit(:name, :email, :message, :captcha)
	end

end

app/controllers/free_beds_controller.rb
class FreeBedsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
  	@free_bed = FreeBed.new
  	@hospital = Hospital.find(params[:hospital_id])
  	@history = FreeBed.where(hospital_id: params[:hospital_id]).reverse


  	if @hospital.free_beds.count != 0 && @hospital.free_beds.last.number
  		@current_nb_beds = @hospital.free_beds.last.number
  	else
  		@current_nb_beds = "Non défini"
  	end
  end

  def create
    @free_bed = FreeBed.new(free_beds_params)
    @hospital = Hospital.find(params[:hospital_id])
    @free_bed.hospital = @hospital
    if @free_bed.save
      redirect_to hospitals_path
    else
      render :new
    end
  end

  private

  def free_beds_params
    params.require(:free_bed).permit(:number)
  end

end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :create, :new]

  def index
		@hospitals = Hospital.geocoded
  	@known_hospitals = Hospital.includes(:free_beds).where.not(free_beds: {id: nil})
  	@pending_hospitals = Hospital.includes(:free_beds).where(free_beds: {id: nil})


    @markers = @hospitals.map do |hospital|
      {
        lat: hospital.latitude,
        lng: hospital.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { hospital: hospital })
      }
    end
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
    @free_bed = FreeBed.new(number: params[:hospital][:free_beds][:number])
    @free_bed.hospital = @hospital
    if @hospital.save && @free_bed.save
      redirect_to hospitals_path, notice: "L'établissement a été enregistré."
    else
      render :new
    end
  end

  private

  def hospital_params
    params.require(:hospital).permit(:name, :contact_infos, :phone, :address, :number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :condition, :mentions]

  def home
  end

  def about
  end

  def condition
  end

  def mentions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
	<h1 class="text-center">Contactez nous</h1>
	<div class="d-flex justify-content-center">
		<div class="col-12 col-md-6">
		  <%= simple_form_for @contact, :html => {class: 'form-horizontal' } do |f| %>
		    <%= f.input :name, required: true, placeholder:"Votre nom", label: false %>
		    <%= f.input :email, required: true, placeholder:"Votre email", label: false %>
		    <%= f.input :message, as: :text, required: true, placeholder:"Votre message", label: false %>
		    <%= invisible_recaptcha_tags text: 'Envoyer', class: "btn btn-primary" %>
		  <% end %>
		</div>
	</div>
</div>

app/views/free_beds/new.html.erb
<%#= simple_form_for(@booking, as: :booking, method: :post, url: chicken_bookings_path(@chicken)) do |f| %>
<%#= simple_form_for(@free_bed, as: :free_bed, method: :post, url: chicken_bookings_path(@chicken)) do |f| %>
<div class="container">
	<h1><%= @hospital.name %></h1>
	<div class="row">
		<div class="col-6">
			<h2>Valeur actuelle :</h2>
			<p><b><%= @current_nb_beds %></b></p>
			<h2>Historique</h2>
			<ul>
			<% @history.each do |free_bed| %>
				<li><%= free_bed.number ? free_bed.number : "non défini" %> (<%= free_bed.updated_at %>)</li>
			<% end %>
			</ul>
		</div>
		<div class="col-6">
			<p>Nouvelle valeur :</p>
			<%= simple_form_for [@hospital, @free_bed] do |f| %>
			  <% if @free_bed.errors.any? %>
			    <p class="text-danger"><%= @free_bed.errors[:free_bed].first  %></p>
			  <% end %>
			  <div class=" form-inputs col-auto">
			    <%= f.input :number, required: true, as: :integer, label:"Nb de lits disponibles" %>
			  </div>
			  <div class="form-actions col-auto">
			    <%#= f.button :submit, "Enregistrer", class: "btn btn-primary" %>
			    <%= invisible_recaptcha_tags text: 'Enregistrer', class: "btn btn-primary" %>
			  </div>
			<% end %>
		</div>
	</div>
</div>

app/views/hospitals/_info_window.html.erb
<b><%= hospital.name %></b><br>
<% if hospital.free_beds.count != 0 && hospital.free_beds.last.number %>
<%= hospital.free_beds.last.number %> lits dispos
<% else %>
nb de lits non défini
<% end %>

app/views/hospitals/index.html.erb
<%# if session[:code] %>
<div class="container">
	<div class="row mt-5">
		<div class="col-12 col-md-8" id="hospital-listing">
			<div class="d-flex flex-column flex-md-row justify-content-between">
				<div class="mb-2">
					<div class="has-search">
				    <span class="fa fa-search form-control-feedback"></span>
						<input class="w-100" type="text" id="searchHospitalInput" placeholder="Chercher un établissement">
				  </div>
				</div>
				<div>
					<%= link_to '<i class="fa fa-plus" aria-hidden="true"></i> Ajouter un établissement'.html_safe, new_hospital_path, class: "btn btn-secondary mb-2" %>
					<%= link_to '<i class="fas fa-map-marked-alt"></i> Voir la map'.html_safe, '#map', class: "btn btn-secondary d-md-none mb-2" %>
				</div>
			</div>
			<div>
				<% @known_hospitals.each do |hospital| %>
					<%= render partial: 'shared/hospital-card', locals: {hospital: hospital } %>
				<% end %>
				<% @pending_hospitals.each do |hospital| %>
					<%= render partial: 'shared/hospital-card', locals: {hospital: hospital } %>
				<% end %>
			</div>
		</div>
		<div class="col-12 col-md-4">
			<div
			  id="map"
			  style="width: 100%;
			  height: 600px;"
			  data-markers="<%= @markers.to_json %>"
			  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
			></div>
		</div>
	</div>
</div>

<%# else %>
<!-- Vous n'avez pas les permissions pour accéder à cette page. -->
<%#= link_to "Retour à l'acceuil", root_path %>
<%# end %>

app/views/hospitals/new.html.erb
<div class="container">
	<h1>Enregistrer un nouvel établissement hopitalier :</h1>
	<%= simple_form_for @hospital do |f| %>
		<% if @hospital.errors.any? %>
			<p class="text-danger"><%= @hospital.errors[:hospital].first  %></p>
		<% end %>
		<%= f.input :name, required: true, placeholder:"Nom de l'établissement", label: false %>
		<%= f.input :address, required: true, placeholder:"Adresse", label: false, input_html: { id:"flat_address" } %>
		<%= f.input :phone, placeholder:"Téléphone", label: false %>
		<%= f.input :contact_infos, placeholder:"Autres informations de contact", label: false %>
		<%= f.simple_fields_for :free_beds do |free_beds_form| %>
    	<%= free_beds_form.input :number, as: :integer, placeholder:"Nombre de lits vides", label: false %>
  	<% end %>

		<%#= f.input :number, placeholder:"Nombre de lits libres", label: false %>
		<%#= f.fields_for @hospital.build_free_beds do |g| %>
    	<%#= g.text_field :number %>
  	<%# end %>
		<%#= f.button :submit, "Enregistrer", class: "btn btn-primary" %>
		<%= invisible_recaptcha_tags text: 'Enregistrer', class: "btn btn-primary" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lits réanimations en France</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <h1 class="text-center">Qui sommes nous?</h1>
  <p>Le projet est à l'initiative de : </p>
  <ul>
    <li>Nicolas Guimier</li>
    <li>Maxime Chenais</li>
    <li>Jérémie Rousseau</li>
  </ul>

  <h3>Comment nous contacter ?</h3>
  <p>Par courriel : contact@lits-reanimation.com</p>

</div>

app/views/pages/condition.html.erb
<div class="container">
	<h1 class="text-center">Conditions générales d'utilisation</h1>
	<p class="text-center"><i>(en vigueur au 04/04/2020)</i></p>
    
  <p>Les présentes conditions générales d'utilisation (dites « CGU ») ont pour objet l'encadrement juridique des modalités de mise à disposition du site et des services par lits-reanimation.com et de définir les conditions d’accès et d’utilisation des services par « l'Utilisateur ».
  Les présentes CGU sont accessibles sur le site à la rubrique «CGU».</p>

    <h2>Article 1 : Les mentions légales</h2>
    <p>L’édition et la direction de la publication du site lits-reanimation.com est assurée par Nicolas Guimier, Maxime Chenais et Jérémie Rousseau.
    Adresse e-mail contact@lits-reanimation.com.
    L'hébergeur du site lits-reanimation.com est la société Clever Cloud, dont le siège social est situé au 3 RUE DE L ALLIER - 44000 NANTES, avec le numéro de téléphone : +33 (0)2 85 52 07 69.</p>

  <h2>ARTICLE 2 : Accès au site</h2>
    <p>Le site lits-reanimation.com permet à l'Utilisateur un accès gratuit aux services suivants :
    Recherche et proposition de lits de réanimation liés à la pandémie COVID-19.
    Le site est accessible gratuitement en tout lieu à tout Utilisateur travaillant au sein d’un établissement de santé public ayant un accès à Internet. Tous les frais supportés par l'Utilisateur pour accéder au service (matériel informatique, logiciels, connexion Internet, etc.) sont à sa charge.</p>

  <h2>ARTICLE 3 : Collecte des données</h2>
   <p> Le site est exempté de déclaration à la Commission Nationale Informatique et Libertés (CNIL) dans la mesure où il ne collecte aucune donnée concernant les Utilisateurs.</p>

  <h2>ARTICLE 4 : Propriété intellectuelle</h2>
    <p>Les marques, logos, signes ainsi que tous les contenus du site (textes, images, son…) font l'objet d'une protection par le Code de la propriété intellectuelle et plus particulièrement par le droit d'auteur.
    L'Utilisateur doit solliciter l'autorisation préalable du site pour toute reproduction, publication, copie des différents contenus. Il s'engage à une utilisation des contenus du site dans un cadre strictement privé, toute utilisation à des fins commerciales et publicitaires est strictement interdite.
    Toute représentation totale ou partielle de ce site par quelque procédé que ce soit, sans l’autorisation expresse de l’exploitant du site Internet constituerait une contrefaçon sanctionnée par l’article L 335-2 et suivants du Code de la propriété intellectuelle.
    Il est rappelé conformément à l’article L122-5 du Code de propriété intellectuelle que l’Utilisateur qui reproduit, copie ou publie le contenu protégé doit citer l’auteur et sa source.</p>

  <h2>ARTICLE 5 : Responsabilité</h2>
    <p>Les sources des informations diffusées sur le site lits-reanimation.com sont réputées fiables mais le site ne garantit pas qu’il soit exempt de défauts, d’erreurs ou d’omissions.
    Les informations communiquées sont présentées à titre indicatif et général sans valeur contractuelle. Malgré des mises à jour régulières, le site lits-reanimation.com ne peut être tenu responsable de la modification des dispositions administratives et juridiques survenant après la publication. De même, le site ne peut être tenue responsable de l’utilisation et de l’interprétation de l’information contenue dans ce site.
    Le site lits-reanimation.com  ne peut être tenu pour responsable d’éventuels virus qui pourraient infecter l’ordinateur ou tout matériel informatique de l’Internaute, suite à une utilisation, à l’accès, ou au téléchargement provenant de ce site.
    La responsabilité du site ne peut être engagée en cas de force majeure ou du fait imprévisible et insurmontable d'un tiers.</p>

  <h2>ARTICLE 6 : Liens hypertextes</h2>
   <p> Des liens hypertextes peuvent être présents sur le site. L’Utilisateur est informé qu’en cliquant sur ces liens, il sortira peut-être du site lits-reanimation.com. Ce dernier n’a pas de contrôle sur les pages web sur lesquelles aboutissent ces liens et ne saurait, en aucun cas, être responsable de leur contenu.</p>

  <h2>ARTICLE 7 : Cookies</h2>
    <p>L’Utilisateur est informé que lors de ses visites sur le site, un cookie peut s’installer automatiquement sur son logiciel de navigation.
    Les cookies sont de petits fichiers stockés temporairement sur le disque dur de l’ordinateur de l’Utilisateur par votre navigateur et qui sont nécessaires à l’utilisation du site lits-reanimation.com. Les cookies ne contiennent pas d’information personnelle et ne peuvent pas être utilisés pour identifier quelqu’un. Un cookie contient un identifiant unique, généré aléatoirement et donc anonyme. Certains cookies expirent à la fin de la visite de l’Utilisateur, d’autres restent.
    L’information contenue dans les cookies est utilisée pour améliorer le site lits-reanimation.com.
    En naviguant sur le site, L’Utilisateur les accepte.
    L’Utilisateur doit toutefois donner son consentement quant à l’utilisation de certains cookies.
    A défaut d’acceptation, l’Utilisateur est informé que certaines fonctionnalités ou pages risquent de lui être refusées.
    L’Utilisateur pourra désactiver ces cookies par l’intermédiaire des paramètres figurant au sein de son logiciel de navigation.</p>

  <h2>ARTICLE 8 : Droit applicable et juridiction compétente</h2>
  <p>La législation française s'applique au présent contrat. En cas d'absence de résolution amiable d'un litige né entre les parties, les tribunaux français seront seuls compétents pour en connaître.
    Pour toute question relative à l’application des présentes CGU, vous pouvez joindre l’éditeur aux coordonnées inscrites à l’ARTICLE 1.</p>
</div>

app/views/pages/home.html.erb
<div class="container text-center mt-3">
  <h4>“<i>Guérir parfois, soulager souvent, écouter toujours.</i>” (L. Pasteur)</h4>
</div>
<div class = "container text-center mt-5">
  <h2>Outil de recherche de lits de réanimation</h2>
</div>
<!-- <div class= "container row pl-5">
  <%#= form_tag(submit_code_path, class:"d-flex justify-content-center mb-5") do %>
  <%#= text_field_tag 'code', nil, placeholder: "Saisissez Votre code", required: true %>
  <%#= invisible_recaptcha_tags text: 'Valider', class: "btn btn-primary" %>
  <%# Code for displaying visible catcha, to click, instead of invisible %>
  <%#= recaptcha_tags %>
  <%#= submit_tag 'Valider', class: "btn btn-primary" %>
  <%# end %>
</div> -->
<div class= "container mt-5">
	<h4>Trouvez les lits disponibles pour réanimation dans le cadre de la lutte contre le Covid-19.</h4>
	<p>Suite au témoignage de nombreux soignants et de leur difficulté à trouver des lits en réanimation disponible, nous avons souhaité proposer un outil simple destiné aux établissements de santé.</p>
	<ul>
	  <li>Vous souhaitez trouver un lit en réanimation disponible sur le territoire ou dans votre région ?</li>
	  <li>Votre établissement dispose de lits disponibles, et vous souhaitez proposer des places en réanimation ?</li>
	</ul>
	<p>Agissez rapidement et commencez votre recherche dès maintenant. Merci de n'utiliser ce service que si vous en êtes destinataire.</p>
</div>
<div class="container text-center h1">
	<%= link_to "Voir la liste des établissements", hospitals_path, class: "btn-lg btn btn-primary" %>
</div>

app/views/pages/mentions.html.erb
<div class="container">
	<h1 class="text-center">Mentions légales</h1>
	<h2>Editeur</h2>
	<ul>
    <li>Nicolas Guimier</li>
    <li>Maxime Chenais</li>
    <li>Jérémie Rousseau</li>
  </ul>

	<h2>Directeur de la publication</h2>
	<p>
		Jérémie Rousseau : contact@lits-reanimation.com
	</p>
	<h2>Hébergeur</h2>
	<p>
	Clever Cloud SAS<br>
	3 rue de l'Allier, 44000 Nantes, France<br>
	RCS Nantes B 524 172 699.
	</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer bg-secondary">
	<div class="container text-center mt-5 p-3">
		<%= link_to "Qui sommes nous ?", about_path %> -
		<%= link_to "Conditions d'utilisation", conditions_path %> -
		<%= link_to "Mentions légales", mentions_legales_path %> -
		<%= link_to "Contact", new_contact_path %>
	</div>
</div>

app/views/shared/_hospital-card.html.erb
<%
	nb_of_beds = "?"
	last_update = hospital.updated_at
	if hospital.free_beds.count != 0 && hospital.free_beds.last.number
		nb_of_beds = hospital.free_beds.last.number.to_s + " <i class='fa fa-procedures'></i>"
		last_update = hospital.free_beds.last.updated_at
	end
%>

<div class="hospital-card">
	<div class="hospital-infos">
		<div class="hospital-text">
			<b><%= hospital.name %></b><br>
			<%= hospital.address %><br>
		</div>
		<div>
			Tel : <%= hospital.phone %><br>
			<i>Mise à jour : <%= last_update %></i>
		</div>
	</div>
	<div class="hospital-beds">
		<div class="number">
		<%= nb_of_beds.html_safe %>
		</div>
		<div class="links">
			<%= link_to "modifier", new_hospital_free_bed_path(hospital) %>
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-5">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dt2lwcp7z/image/upload/v1585993556/lits-reanimation.com/logo_qu3dwo.png" %>
    Lits-Réanimation.com
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
        	<%= link_to "Tous les établissements", hospitals_path, class: "nav-link" %>
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>